/* eslint-disable */
// this is an auto generated file. This will be overwritten

export const createCommunity = `mutation CreateCommunity($input: CreateCommunityInput!) {
  createCommunity(input: $input) {
    id
    url
    name
    description
    creator
    created_date
    rules
    locations
    hidden
    hidden_date
    sitewide_reasons_for_being_hidden
    keywords
    tags
    flagged_comments {
      id
      content
      author
      thread_id
      created_date
      hidden
      hidden_date
      sitewide_reasons_for_being_hidden
      community_reasons_for_being_hidden
      contributed_to_discussion
      did_not_contribute_to_discussion
      agree
      disagree
      funny
      date_last_modified
      parent_comment_id
    }
    flagged_discussions {
      id
      headline
      creator {
        id
        email
      }
      created_date
      date_last_edited
      description
      locked
      hidden
      sitewide_reasons_for_being_hidden
      community_reasons_for_being_hidden
      hidden_date
      upvotes
      downvotes
      keywords
    }
    moderation_level
    number_of_users
  }
}
`;
export const updateCommunity = `mutation UpdateCommunity($input: UpdateCommunityInput!) {
  updateCommunity(input: $input) {
    id
    url
    name
    description
    creator
    created_date
    rules
    locations
    hidden
    hidden_date
    sitewide_reasons_for_being_hidden
    keywords
    tags
    flagged_comments {
      id
      content
      author
      thread_id
      created_date
      hidden
      hidden_date
      sitewide_reasons_for_being_hidden
      community_reasons_for_being_hidden
      contributed_to_discussion
      did_not_contribute_to_discussion
      agree
      disagree
      funny
      date_last_modified
      parent_comment_id
    }
    flagged_discussions {
      id
      headline
      creator {
        id
        email
      }
      created_date
      date_last_edited
      description
      locked
      hidden
      sitewide_reasons_for_being_hidden
      community_reasons_for_being_hidden
      hidden_date
      upvotes
      downvotes
      keywords
    }
    moderation_level
    number_of_users
  }
}
`;
export const deleteCommunity = `mutation DeleteCommunity($input: DeleteCommunityInput!) {
  deleteCommunity(input: $input) {
    id
    url
    name
    description
    creator
    created_date
    rules
    locations
    hidden
    hidden_date
    sitewide_reasons_for_being_hidden
    keywords
    tags
    flagged_comments {
      id
      content
      author
      thread_id
      created_date
      hidden
      hidden_date
      sitewide_reasons_for_being_hidden
      community_reasons_for_being_hidden
      contributed_to_discussion
      did_not_contribute_to_discussion
      agree
      disagree
      funny
      date_last_modified
      parent_comment_id
    }
    flagged_discussions {
      id
      headline
      creator {
        id
        email
      }
      created_date
      date_last_edited
      description
      locked
      hidden
      sitewide_reasons_for_being_hidden
      community_reasons_for_being_hidden
      hidden_date
      upvotes
      downvotes
      keywords
    }
    moderation_level
    number_of_users
  }
}
`;
export const createBan = `mutation CreateBan($input: CreateBanInput!) {
  createBan(input: $input) {
    id
    user {
      id
      email
      profiles {
        id
        username
        real_sounding_name
        bio
        pronouns
        location
        picture
        reputation
        account_created_date
      }
      default_profile {
        id
        username
        real_sounding_name
        bio
        pronouns
        location
        picture
        reputation
        account_created_date
      }
    }
    is_sitewide_ban
    community {
      id
      url
      name
      description
      creator
      created_date
      rules
      locations
      hidden
      hidden_date
      sitewide_reasons_for_being_hidden
      keywords
      tags
      flagged_comments {
        id
        content
        author
        thread_id
        created_date
        hidden
        hidden_date
        sitewide_reasons_for_being_hidden
        community_reasons_for_being_hidden
        contributed_to_discussion
        did_not_contribute_to_discussion
        agree
        disagree
        funny
        date_last_modified
        parent_comment_id
      }
      flagged_discussions {
        id
        headline
        created_date
        date_last_edited
        description
        locked
        hidden
        sitewide_reasons_for_being_hidden
        community_reasons_for_being_hidden
        hidden_date
        upvotes
        downvotes
        keywords
      }
      moderation_level
      number_of_users
    }
    createdDate
    expirationDate
  }
}
`;
export const updateBan = `mutation UpdateBan($input: UpdateBanInput!) {
  updateBan(input: $input) {
    id
    user {
      id
      email
      profiles {
        id
        username
        real_sounding_name
        bio
        pronouns
        location
        picture
        reputation
        account_created_date
      }
      default_profile {
        id
        username
        real_sounding_name
        bio
        pronouns
        location
        picture
        reputation
        account_created_date
      }
    }
    is_sitewide_ban
    community {
      id
      url
      name
      description
      creator
      created_date
      rules
      locations
      hidden
      hidden_date
      sitewide_reasons_for_being_hidden
      keywords
      tags
      flagged_comments {
        id
        content
        author
        thread_id
        created_date
        hidden
        hidden_date
        sitewide_reasons_for_being_hidden
        community_reasons_for_being_hidden
        contributed_to_discussion
        did_not_contribute_to_discussion
        agree
        disagree
        funny
        date_last_modified
        parent_comment_id
      }
      flagged_discussions {
        id
        headline
        created_date
        date_last_edited
        description
        locked
        hidden
        sitewide_reasons_for_being_hidden
        community_reasons_for_being_hidden
        hidden_date
        upvotes
        downvotes
        keywords
      }
      moderation_level
      number_of_users
    }
    createdDate
    expirationDate
  }
}
`;
export const deleteBan = `mutation DeleteBan($input: DeleteBanInput!) {
  deleteBan(input: $input) {
    id
    user {
      id
      email
      profiles {
        id
        username
        real_sounding_name
        bio
        pronouns
        location
        picture
        reputation
        account_created_date
      }
      default_profile {
        id
        username
        real_sounding_name
        bio
        pronouns
        location
        picture
        reputation
        account_created_date
      }
    }
    is_sitewide_ban
    community {
      id
      url
      name
      description
      creator
      created_date
      rules
      locations
      hidden
      hidden_date
      sitewide_reasons_for_being_hidden
      keywords
      tags
      flagged_comments {
        id
        content
        author
        thread_id
        created_date
        hidden
        hidden_date
        sitewide_reasons_for_being_hidden
        community_reasons_for_being_hidden
        contributed_to_discussion
        did_not_contribute_to_discussion
        agree
        disagree
        funny
        date_last_modified
        parent_comment_id
      }
      flagged_discussions {
        id
        headline
        created_date
        date_last_edited
        description
        locked
        hidden
        sitewide_reasons_for_being_hidden
        community_reasons_for_being_hidden
        hidden_date
        upvotes
        downvotes
        keywords
      }
      moderation_level
      number_of_users
    }
    createdDate
    expirationDate
  }
}
`;
export const createComment = `mutation CreateComment($input: CreateCommentInput!) {
  createComment(input: $input) {
    id
    content
    author
    thread_id
    created_date
    hidden
    hidden_date
    sitewide_reasons_for_being_hidden
    community_reasons_for_being_hidden
    contributed_to_discussion
    did_not_contribute_to_discussion
    agree
    disagree
    funny
    date_last_modified
    parent_comment_id
  }
}
`;
export const updateComment = `mutation UpdateComment($input: UpdateCommentInput!) {
  updateComment(input: $input) {
    id
    content
    author
    thread_id
    created_date
    hidden
    hidden_date
    sitewide_reasons_for_being_hidden
    community_reasons_for_being_hidden
    contributed_to_discussion
    did_not_contribute_to_discussion
    agree
    disagree
    funny
    date_last_modified
    parent_comment_id
  }
}
`;
export const deleteComment = `mutation DeleteComment($input: DeleteCommentInput!) {
  deleteComment(input: $input) {
    id
    content
    author
    thread_id
    created_date
    hidden
    hidden_date
    sitewide_reasons_for_being_hidden
    community_reasons_for_being_hidden
    contributed_to_discussion
    did_not_contribute_to_discussion
    agree
    disagree
    funny
    date_last_modified
    parent_comment_id
  }
}
`;
export const createDiscussion = `mutation CreateDiscussion($input: CreateDiscussionInput!) {
  createDiscussion(input: $input) {
    id
    headline
    creator {
      id
      email
      profiles {
        id
        username
        real_sounding_name
        bio
        pronouns
        location
        picture
        reputation
        account_created_date
      }
      default_profile {
        id
        username
        real_sounding_name
        bio
        pronouns
        location
        picture
        reputation
        account_created_date
      }
    }
    created_date
    date_last_edited
    description
    locked
    hidden
    sitewide_reasons_for_being_hidden
    community_reasons_for_being_hidden
    hidden_date
    upvotes
    downvotes
    keywords
  }
}
`;
export const updateDiscussion = `mutation UpdateDiscussion($input: UpdateDiscussionInput!) {
  updateDiscussion(input: $input) {
    id
    headline
    creator {
      id
      email
      profiles {
        id
        username
        real_sounding_name
        bio
        pronouns
        location
        picture
        reputation
        account_created_date
      }
      default_profile {
        id
        username
        real_sounding_name
        bio
        pronouns
        location
        picture
        reputation
        account_created_date
      }
    }
    created_date
    date_last_edited
    description
    locked
    hidden
    sitewide_reasons_for_being_hidden
    community_reasons_for_being_hidden
    hidden_date
    upvotes
    downvotes
    keywords
  }
}
`;
export const deleteDiscussion = `mutation DeleteDiscussion($input: DeleteDiscussionInput!) {
  deleteDiscussion(input: $input) {
    id
    headline
    creator {
      id
      email
      profiles {
        id
        username
        real_sounding_name
        bio
        pronouns
        location
        picture
        reputation
        account_created_date
      }
      default_profile {
        id
        username
        real_sounding_name
        bio
        pronouns
        location
        picture
        reputation
        account_created_date
      }
    }
    created_date
    date_last_edited
    description
    locked
    hidden
    sitewide_reasons_for_being_hidden
    community_reasons_for_being_hidden
    hidden_date
    upvotes
    downvotes
    keywords
  }
}
`;
export const createEvent = `mutation CreateEvent($input: CreateEventInput!) {
  createEvent(input: $input) {
    id
    title
    description
    picture
    start_time
    end_time
    place {
      id
      url
      name
      description
      creator
      created_date
      rules
      locations
      hidden
      hidden_date
      sitewide_reasons_for_being_hidden
      keywords
      tags
      flagged_comments {
        id
        content
        author
        thread_id
        created_date
        hidden
        hidden_date
        sitewide_reasons_for_being_hidden
        community_reasons_for_being_hidden
        contributed_to_discussion
        did_not_contribute_to_discussion
        agree
        disagree
        funny
        date_last_modified
        parent_comment_id
      }
      flagged_discussions {
        id
        headline
        created_date
        date_last_edited
        description
        locked
        hidden
        sitewide_reasons_for_being_hidden
        community_reasons_for_being_hidden
        hidden_date
        upvotes
        downvotes
        keywords
      }
      moderation_level
      number_of_users
    }
    organizer {
      id
      email
      profiles {
        id
        username
        real_sounding_name
        bio
        pronouns
        location
        picture
        reputation
        account_created_date
      }
      default_profile {
        id
        username
        real_sounding_name
        bio
        pronouns
        location
        picture
        reputation
        account_created_date
      }
    }
  }
}
`;
export const updateEvent = `mutation UpdateEvent($input: UpdateEventInput!) {
  updateEvent(input: $input) {
    id
    title
    description
    picture
    start_time
    end_time
    place {
      id
      url
      name
      description
      creator
      created_date
      rules
      locations
      hidden
      hidden_date
      sitewide_reasons_for_being_hidden
      keywords
      tags
      flagged_comments {
        id
        content
        author
        thread_id
        created_date
        hidden
        hidden_date
        sitewide_reasons_for_being_hidden
        community_reasons_for_being_hidden
        contributed_to_discussion
        did_not_contribute_to_discussion
        agree
        disagree
        funny
        date_last_modified
        parent_comment_id
      }
      flagged_discussions {
        id
        headline
        created_date
        date_last_edited
        description
        locked
        hidden
        sitewide_reasons_for_being_hidden
        community_reasons_for_being_hidden
        hidden_date
        upvotes
        downvotes
        keywords
      }
      moderation_level
      number_of_users
    }
    organizer {
      id
      email
      profiles {
        id
        username
        real_sounding_name
        bio
        pronouns
        location
        picture
        reputation
        account_created_date
      }
      default_profile {
        id
        username
        real_sounding_name
        bio
        pronouns
        location
        picture
        reputation
        account_created_date
      }
    }
  }
}
`;
export const deleteEvent = `mutation DeleteEvent($input: DeleteEventInput!) {
  deleteEvent(input: $input) {
    id
    title
    description
    picture
    start_time
    end_time
    place {
      id
      url
      name
      description
      creator
      created_date
      rules
      locations
      hidden
      hidden_date
      sitewide_reasons_for_being_hidden
      keywords
      tags
      flagged_comments {
        id
        content
        author
        thread_id
        created_date
        hidden
        hidden_date
        sitewide_reasons_for_being_hidden
        community_reasons_for_being_hidden
        contributed_to_discussion
        did_not_contribute_to_discussion
        agree
        disagree
        funny
        date_last_modified
        parent_comment_id
      }
      flagged_discussions {
        id
        headline
        created_date
        date_last_edited
        description
        locked
        hidden
        sitewide_reasons_for_being_hidden
        community_reasons_for_being_hidden
        hidden_date
        upvotes
        downvotes
        keywords
      }
      moderation_level
      number_of_users
    }
    organizer {
      id
      email
      profiles {
        id
        username
        real_sounding_name
        bio
        pronouns
        location
        picture
        reputation
        account_created_date
      }
      default_profile {
        id
        username
        real_sounding_name
        bio
        pronouns
        location
        picture
        reputation
        account_created_date
      }
    }
  }
}
`;
export const createPrivateMessage = `mutation CreatePrivateMessage($input: CreatePrivateMessageInput!) {
  createPrivateMessage(input: $input) {
    id
    title
    content
    author {
      id
      email
      profiles {
        id
        username
        real_sounding_name
        bio
        pronouns
        location
        picture
        reputation
        account_created_date
      }
      default_profile {
        id
        username
        real_sounding_name
        bio
        pronouns
        location
        picture
        reputation
        account_created_date
      }
    }
    sentDate
  }
}
`;
export const updatePrivateMessage = `mutation UpdatePrivateMessage($input: UpdatePrivateMessageInput!) {
  updatePrivateMessage(input: $input) {
    id
    title
    content
    author {
      id
      email
      profiles {
        id
        username
        real_sounding_name
        bio
        pronouns
        location
        picture
        reputation
        account_created_date
      }
      default_profile {
        id
        username
        real_sounding_name
        bio
        pronouns
        location
        picture
        reputation
        account_created_date
      }
    }
    sentDate
  }
}
`;
export const deletePrivateMessage = `mutation DeletePrivateMessage($input: DeletePrivateMessageInput!) {
  deletePrivateMessage(input: $input) {
    id
    title
    content
    author {
      id
      email
      profiles {
        id
        username
        real_sounding_name
        bio
        pronouns
        location
        picture
        reputation
        account_created_date
      }
      default_profile {
        id
        username
        real_sounding_name
        bio
        pronouns
        location
        picture
        reputation
        account_created_date
      }
    }
    sentDate
  }
}
`;
export const createReport = `mutation CreateReport($input: CreateReportInput!) {
  createReport(input: $input) {
    id
    creator
    comment {
      id
      content
      author
      thread_id
      created_date
      hidden
      hidden_date
      sitewide_reasons_for_being_hidden
      community_reasons_for_being_hidden
      contributed_to_discussion
      did_not_contribute_to_discussion
      agree
      disagree
      funny
      date_last_modified
      parent_comment_id
    }
    discussion {
      id
      headline
      creator {
        id
        email
      }
      created_date
      date_last_edited
      description
      locked
      hidden
      sitewide_reasons_for_being_hidden
      community_reasons_for_being_hidden
      hidden_date
      upvotes
      downvotes
      keywords
    }
    message {
      id
      title
      content
      author {
        id
        email
      }
      sentDate
    }
    complaint
    community {
      id
      url
      name
      description
      creator
      created_date
      rules
      locations
      hidden
      hidden_date
      sitewide_reasons_for_being_hidden
      keywords
      tags
      flagged_comments {
        id
        content
        author
        thread_id
        created_date
        hidden
        hidden_date
        sitewide_reasons_for_being_hidden
        community_reasons_for_being_hidden
        contributed_to_discussion
        did_not_contribute_to_discussion
        agree
        disagree
        funny
        date_last_modified
        parent_comment_id
      }
      flagged_discussions {
        id
        headline
        created_date
        date_last_edited
        description
        locked
        hidden
        sitewide_reasons_for_being_hidden
        community_reasons_for_being_hidden
        hidden_date
        upvotes
        downvotes
        keywords
      }
      moderation_level
      number_of_users
    }
    broken_sitewide_rules
    broken_community_rules
    author {
      id
      email
      profiles {
        id
        username
        real_sounding_name
        bio
        pronouns
        location
        picture
        reputation
        account_created_date
      }
      default_profile {
        id
        username
        real_sounding_name
        bio
        pronouns
        location
        picture
        reputation
        account_created_date
      }
    }
    created_date
    resolved
  }
}
`;
export const updateReport = `mutation UpdateReport($input: UpdateReportInput!) {
  updateReport(input: $input) {
    id
    creator
    comment {
      id
      content
      author
      thread_id
      created_date
      hidden
      hidden_date
      sitewide_reasons_for_being_hidden
      community_reasons_for_being_hidden
      contributed_to_discussion
      did_not_contribute_to_discussion
      agree
      disagree
      funny
      date_last_modified
      parent_comment_id
    }
    discussion {
      id
      headline
      creator {
        id
        email
      }
      created_date
      date_last_edited
      description
      locked
      hidden
      sitewide_reasons_for_being_hidden
      community_reasons_for_being_hidden
      hidden_date
      upvotes
      downvotes
      keywords
    }
    message {
      id
      title
      content
      author {
        id
        email
      }
      sentDate
    }
    complaint
    community {
      id
      url
      name
      description
      creator
      created_date
      rules
      locations
      hidden
      hidden_date
      sitewide_reasons_for_being_hidden
      keywords
      tags
      flagged_comments {
        id
        content
        author
        thread_id
        created_date
        hidden
        hidden_date
        sitewide_reasons_for_being_hidden
        community_reasons_for_being_hidden
        contributed_to_discussion
        did_not_contribute_to_discussion
        agree
        disagree
        funny
        date_last_modified
        parent_comment_id
      }
      flagged_discussions {
        id
        headline
        created_date
        date_last_edited
        description
        locked
        hidden
        sitewide_reasons_for_being_hidden
        community_reasons_for_being_hidden
        hidden_date
        upvotes
        downvotes
        keywords
      }
      moderation_level
      number_of_users
    }
    broken_sitewide_rules
    broken_community_rules
    author {
      id
      email
      profiles {
        id
        username
        real_sounding_name
        bio
        pronouns
        location
        picture
        reputation
        account_created_date
      }
      default_profile {
        id
        username
        real_sounding_name
        bio
        pronouns
        location
        picture
        reputation
        account_created_date
      }
    }
    created_date
    resolved
  }
}
`;
export const deleteReport = `mutation DeleteReport($input: DeleteReportInput!) {
  deleteReport(input: $input) {
    id
    creator
    comment {
      id
      content
      author
      thread_id
      created_date
      hidden
      hidden_date
      sitewide_reasons_for_being_hidden
      community_reasons_for_being_hidden
      contributed_to_discussion
      did_not_contribute_to_discussion
      agree
      disagree
      funny
      date_last_modified
      parent_comment_id
    }
    discussion {
      id
      headline
      creator {
        id
        email
      }
      created_date
      date_last_edited
      description
      locked
      hidden
      sitewide_reasons_for_being_hidden
      community_reasons_for_being_hidden
      hidden_date
      upvotes
      downvotes
      keywords
    }
    message {
      id
      title
      content
      author {
        id
        email
      }
      sentDate
    }
    complaint
    community {
      id
      url
      name
      description
      creator
      created_date
      rules
      locations
      hidden
      hidden_date
      sitewide_reasons_for_being_hidden
      keywords
      tags
      flagged_comments {
        id
        content
        author
        thread_id
        created_date
        hidden
        hidden_date
        sitewide_reasons_for_being_hidden
        community_reasons_for_being_hidden
        contributed_to_discussion
        did_not_contribute_to_discussion
        agree
        disagree
        funny
        date_last_modified
        parent_comment_id
      }
      flagged_discussions {
        id
        headline
        created_date
        date_last_edited
        description
        locked
        hidden
        sitewide_reasons_for_being_hidden
        community_reasons_for_being_hidden
        hidden_date
        upvotes
        downvotes
        keywords
      }
      moderation_level
      number_of_users
    }
    broken_sitewide_rules
    broken_community_rules
    author {
      id
      email
      profiles {
        id
        username
        real_sounding_name
        bio
        pronouns
        location
        picture
        reputation
        account_created_date
      }
      default_profile {
        id
        username
        real_sounding_name
        bio
        pronouns
        location
        picture
        reputation
        account_created_date
      }
    }
    created_date
    resolved
  }
}
`;
export const createUser = `mutation CreateUser($input: CreateUserInput!) {
  createUser(input: $input) {
    id
    email
    profiles {
      id
      username
      real_sounding_name
      bio
      pronouns
      location
      picture
      reputation
      account_created_date
      bans {
        id
        is_sitewide_ban
        createdDate
        expirationDate
      }
      member_of {
        id
        url
        name
        description
        creator
        created_date
        rules
        locations
        hidden
        hidden_date
        sitewide_reasons_for_being_hidden
        keywords
        tags
        moderation_level
        number_of_users
      }
      moderator_of {
        id
        url
        name
        description
        creator
        created_date
        rules
        locations
        hidden
        hidden_date
        sitewide_reasons_for_being_hidden
        keywords
        tags
        moderation_level
        number_of_users
      }
      creator_of {
        id
        url
        name
        description
        creator
        created_date
        rules
        locations
        hidden
        hidden_date
        sitewide_reasons_for_being_hidden
        keywords
        tags
        moderation_level
        number_of_users
      }
    }
    default_profile {
      id
      username
      real_sounding_name
      bio
      pronouns
      location
      picture
      reputation
      account_created_date
      bans {
        id
        is_sitewide_ban
        createdDate
        expirationDate
      }
      member_of {
        id
        url
        name
        description
        creator
        created_date
        rules
        locations
        hidden
        hidden_date
        sitewide_reasons_for_being_hidden
        keywords
        tags
        moderation_level
        number_of_users
      }
      moderator_of {
        id
        url
        name
        description
        creator
        created_date
        rules
        locations
        hidden
        hidden_date
        sitewide_reasons_for_being_hidden
        keywords
        tags
        moderation_level
        number_of_users
      }
      creator_of {
        id
        url
        name
        description
        creator
        created_date
        rules
        locations
        hidden
        hidden_date
        sitewide_reasons_for_being_hidden
        keywords
        tags
        moderation_level
        number_of_users
      }
    }
  }
}
`;
export const updateUser = `mutation UpdateUser($input: UpdateUserInput!) {
  updateUser(input: $input) {
    id
    email
    profiles {
      id
      username
      real_sounding_name
      bio
      pronouns
      location
      picture
      reputation
      account_created_date
      bans {
        id
        is_sitewide_ban
        createdDate
        expirationDate
      }
      member_of {
        id
        url
        name
        description
        creator
        created_date
        rules
        locations
        hidden
        hidden_date
        sitewide_reasons_for_being_hidden
        keywords
        tags
        moderation_level
        number_of_users
      }
      moderator_of {
        id
        url
        name
        description
        creator
        created_date
        rules
        locations
        hidden
        hidden_date
        sitewide_reasons_for_being_hidden
        keywords
        tags
        moderation_level
        number_of_users
      }
      creator_of {
        id
        url
        name
        description
        creator
        created_date
        rules
        locations
        hidden
        hidden_date
        sitewide_reasons_for_being_hidden
        keywords
        tags
        moderation_level
        number_of_users
      }
    }
    default_profile {
      id
      username
      real_sounding_name
      bio
      pronouns
      location
      picture
      reputation
      account_created_date
      bans {
        id
        is_sitewide_ban
        createdDate
        expirationDate
      }
      member_of {
        id
        url
        name
        description
        creator
        created_date
        rules
        locations
        hidden
        hidden_date
        sitewide_reasons_for_being_hidden
        keywords
        tags
        moderation_level
        number_of_users
      }
      moderator_of {
        id
        url
        name
        description
        creator
        created_date
        rules
        locations
        hidden
        hidden_date
        sitewide_reasons_for_being_hidden
        keywords
        tags
        moderation_level
        number_of_users
      }
      creator_of {
        id
        url
        name
        description
        creator
        created_date
        rules
        locations
        hidden
        hidden_date
        sitewide_reasons_for_being_hidden
        keywords
        tags
        moderation_level
        number_of_users
      }
    }
  }
}
`;
export const deleteUser = `mutation DeleteUser($input: DeleteUserInput!) {
  deleteUser(input: $input) {
    id
    email
    profiles {
      id
      username
      real_sounding_name
      bio
      pronouns
      location
      picture
      reputation
      account_created_date
      bans {
        id
        is_sitewide_ban
        createdDate
        expirationDate
      }
      member_of {
        id
        url
        name
        description
        creator
        created_date
        rules
        locations
        hidden
        hidden_date
        sitewide_reasons_for_being_hidden
        keywords
        tags
        moderation_level
        number_of_users
      }
      moderator_of {
        id
        url
        name
        description
        creator
        created_date
        rules
        locations
        hidden
        hidden_date
        sitewide_reasons_for_being_hidden
        keywords
        tags
        moderation_level
        number_of_users
      }
      creator_of {
        id
        url
        name
        description
        creator
        created_date
        rules
        locations
        hidden
        hidden_date
        sitewide_reasons_for_being_hidden
        keywords
        tags
        moderation_level
        number_of_users
      }
    }
    default_profile {
      id
      username
      real_sounding_name
      bio
      pronouns
      location
      picture
      reputation
      account_created_date
      bans {
        id
        is_sitewide_ban
        createdDate
        expirationDate
      }
      member_of {
        id
        url
        name
        description
        creator
        created_date
        rules
        locations
        hidden
        hidden_date
        sitewide_reasons_for_being_hidden
        keywords
        tags
        moderation_level
        number_of_users
      }
      moderator_of {
        id
        url
        name
        description
        creator
        created_date
        rules
        locations
        hidden
        hidden_date
        sitewide_reasons_for_being_hidden
        keywords
        tags
        moderation_level
        number_of_users
      }
      creator_of {
        id
        url
        name
        description
        creator
        created_date
        rules
        locations
        hidden
        hidden_date
        sitewide_reasons_for_being_hidden
        keywords
        tags
        moderation_level
        number_of_users
      }
    }
  }
}
`;
export const createProfile = `mutation CreateProfile($input: CreateProfileInput!) {
  createProfile(input: $input) {
    id
    username
    real_sounding_name
    bio
    pronouns
    location
    picture
    reputation
    account_created_date
    bans {
      id
      user {
        id
        email
      }
      is_sitewide_ban
      community {
        id
        url
        name
        description
        creator
        created_date
        rules
        locations
        hidden
        hidden_date
        sitewide_reasons_for_being_hidden
        keywords
        tags
        moderation_level
        number_of_users
      }
      createdDate
      expirationDate
    }
    member_of {
      id
      url
      name
      description
      creator
      created_date
      rules
      locations
      hidden
      hidden_date
      sitewide_reasons_for_being_hidden
      keywords
      tags
      flagged_comments {
        id
        content
        author
        thread_id
        created_date
        hidden
        hidden_date
        sitewide_reasons_for_being_hidden
        community_reasons_for_being_hidden
        contributed_to_discussion
        did_not_contribute_to_discussion
        agree
        disagree
        funny
        date_last_modified
        parent_comment_id
      }
      flagged_discussions {
        id
        headline
        created_date
        date_last_edited
        description
        locked
        hidden
        sitewide_reasons_for_being_hidden
        community_reasons_for_being_hidden
        hidden_date
        upvotes
        downvotes
        keywords
      }
      moderation_level
      number_of_users
    }
    moderator_of {
      id
      url
      name
      description
      creator
      created_date
      rules
      locations
      hidden
      hidden_date
      sitewide_reasons_for_being_hidden
      keywords
      tags
      flagged_comments {
        id
        content
        author
        thread_id
        created_date
        hidden
        hidden_date
        sitewide_reasons_for_being_hidden
        community_reasons_for_being_hidden
        contributed_to_discussion
        did_not_contribute_to_discussion
        agree
        disagree
        funny
        date_last_modified
        parent_comment_id
      }
      flagged_discussions {
        id
        headline
        created_date
        date_last_edited
        description
        locked
        hidden
        sitewide_reasons_for_being_hidden
        community_reasons_for_being_hidden
        hidden_date
        upvotes
        downvotes
        keywords
      }
      moderation_level
      number_of_users
    }
    creator_of {
      id
      url
      name
      description
      creator
      created_date
      rules
      locations
      hidden
      hidden_date
      sitewide_reasons_for_being_hidden
      keywords
      tags
      flagged_comments {
        id
        content
        author
        thread_id
        created_date
        hidden
        hidden_date
        sitewide_reasons_for_being_hidden
        community_reasons_for_being_hidden
        contributed_to_discussion
        did_not_contribute_to_discussion
        agree
        disagree
        funny
        date_last_modified
        parent_comment_id
      }
      flagged_discussions {
        id
        headline
        created_date
        date_last_edited
        description
        locked
        hidden
        sitewide_reasons_for_being_hidden
        community_reasons_for_being_hidden
        hidden_date
        upvotes
        downvotes
        keywords
      }
      moderation_level
      number_of_users
    }
  }
}
`;
export const updateProfile = `mutation UpdateProfile($input: UpdateProfileInput!) {
  updateProfile(input: $input) {
    id
    username
    real_sounding_name
    bio
    pronouns
    location
    picture
    reputation
    account_created_date
    bans {
      id
      user {
        id
        email
      }
      is_sitewide_ban
      community {
        id
        url
        name
        description
        creator
        created_date
        rules
        locations
        hidden
        hidden_date
        sitewide_reasons_for_being_hidden
        keywords
        tags
        moderation_level
        number_of_users
      }
      createdDate
      expirationDate
    }
    member_of {
      id
      url
      name
      description
      creator
      created_date
      rules
      locations
      hidden
      hidden_date
      sitewide_reasons_for_being_hidden
      keywords
      tags
      flagged_comments {
        id
        content
        author
        thread_id
        created_date
        hidden
        hidden_date
        sitewide_reasons_for_being_hidden
        community_reasons_for_being_hidden
        contributed_to_discussion
        did_not_contribute_to_discussion
        agree
        disagree
        funny
        date_last_modified
        parent_comment_id
      }
      flagged_discussions {
        id
        headline
        created_date
        date_last_edited
        description
        locked
        hidden
        sitewide_reasons_for_being_hidden
        community_reasons_for_being_hidden
        hidden_date
        upvotes
        downvotes
        keywords
      }
      moderation_level
      number_of_users
    }
    moderator_of {
      id
      url
      name
      description
      creator
      created_date
      rules
      locations
      hidden
      hidden_date
      sitewide_reasons_for_being_hidden
      keywords
      tags
      flagged_comments {
        id
        content
        author
        thread_id
        created_date
        hidden
        hidden_date
        sitewide_reasons_for_being_hidden
        community_reasons_for_being_hidden
        contributed_to_discussion
        did_not_contribute_to_discussion
        agree
        disagree
        funny
        date_last_modified
        parent_comment_id
      }
      flagged_discussions {
        id
        headline
        created_date
        date_last_edited
        description
        locked
        hidden
        sitewide_reasons_for_being_hidden
        community_reasons_for_being_hidden
        hidden_date
        upvotes
        downvotes
        keywords
      }
      moderation_level
      number_of_users
    }
    creator_of {
      id
      url
      name
      description
      creator
      created_date
      rules
      locations
      hidden
      hidden_date
      sitewide_reasons_for_being_hidden
      keywords
      tags
      flagged_comments {
        id
        content
        author
        thread_id
        created_date
        hidden
        hidden_date
        sitewide_reasons_for_being_hidden
        community_reasons_for_being_hidden
        contributed_to_discussion
        did_not_contribute_to_discussion
        agree
        disagree
        funny
        date_last_modified
        parent_comment_id
      }
      flagged_discussions {
        id
        headline
        created_date
        date_last_edited
        description
        locked
        hidden
        sitewide_reasons_for_being_hidden
        community_reasons_for_being_hidden
        hidden_date
        upvotes
        downvotes
        keywords
      }
      moderation_level
      number_of_users
    }
  }
}
`;
export const deleteProfile = `mutation DeleteProfile($input: DeleteProfileInput!) {
  deleteProfile(input: $input) {
    id
    username
    real_sounding_name
    bio
    pronouns
    location
    picture
    reputation
    account_created_date
    bans {
      id
      user {
        id
        email
      }
      is_sitewide_ban
      community {
        id
        url
        name
        description
        creator
        created_date
        rules
        locations
        hidden
        hidden_date
        sitewide_reasons_for_being_hidden
        keywords
        tags
        moderation_level
        number_of_users
      }
      createdDate
      expirationDate
    }
    member_of {
      id
      url
      name
      description
      creator
      created_date
      rules
      locations
      hidden
      hidden_date
      sitewide_reasons_for_being_hidden
      keywords
      tags
      flagged_comments {
        id
        content
        author
        thread_id
        created_date
        hidden
        hidden_date
        sitewide_reasons_for_being_hidden
        community_reasons_for_being_hidden
        contributed_to_discussion
        did_not_contribute_to_discussion
        agree
        disagree
        funny
        date_last_modified
        parent_comment_id
      }
      flagged_discussions {
        id
        headline
        created_date
        date_last_edited
        description
        locked
        hidden
        sitewide_reasons_for_being_hidden
        community_reasons_for_being_hidden
        hidden_date
        upvotes
        downvotes
        keywords
      }
      moderation_level
      number_of_users
    }
    moderator_of {
      id
      url
      name
      description
      creator
      created_date
      rules
      locations
      hidden
      hidden_date
      sitewide_reasons_for_being_hidden
      keywords
      tags
      flagged_comments {
        id
        content
        author
        thread_id
        created_date
        hidden
        hidden_date
        sitewide_reasons_for_being_hidden
        community_reasons_for_being_hidden
        contributed_to_discussion
        did_not_contribute_to_discussion
        agree
        disagree
        funny
        date_last_modified
        parent_comment_id
      }
      flagged_discussions {
        id
        headline
        created_date
        date_last_edited
        description
        locked
        hidden
        sitewide_reasons_for_being_hidden
        community_reasons_for_being_hidden
        hidden_date
        upvotes
        downvotes
        keywords
      }
      moderation_level
      number_of_users
    }
    creator_of {
      id
      url
      name
      description
      creator
      created_date
      rules
      locations
      hidden
      hidden_date
      sitewide_reasons_for_being_hidden
      keywords
      tags
      flagged_comments {
        id
        content
        author
        thread_id
        created_date
        hidden
        hidden_date
        sitewide_reasons_for_being_hidden
        community_reasons_for_being_hidden
        contributed_to_discussion
        did_not_contribute_to_discussion
        agree
        disagree
        funny
        date_last_modified
        parent_comment_id
      }
      flagged_discussions {
        id
        headline
        created_date
        date_last_edited
        description
        locked
        hidden
        sitewide_reasons_for_being_hidden
        community_reasons_for_being_hidden
        hidden_date
        upvotes
        downvotes
        keywords
      }
      moderation_level
      number_of_users
    }
  }
}
`;
