/* eslint-disable */
// this is an auto generated file. This will be overwritten

export const onCreateCommunity = `subscription OnCreateCommunity {
  onCreateCommunity {
    id
    url
    name
    description
    creator
    created_date
    rules {
      id
      community_id
      summary
      explanation
    }
    locations
    hidden
    hidden_date
    sitewide_reasons_for_being_hidden
    keywords
    tags
    flagged_comments {
      id
      content
      creator
      discussionId
      created_date
      hidden
      hidden_date
      sitewide_reasons_for_being_hidden
      community_reasons_for_being_hidden
      contributed_to_discussion
      did_not_contribute_to_discussion
      agree
      disagree
      funny
      date_last_modified
      parent_comment_id
    }
    flagged_discussions {
      id
      title
      creator
      communityUrl
      createdDate
      content
      locked
      hidden
      sitewide_reasons_for_being_hidden
      community_reasons_for_being_hidden
      hidden_date
      upvotes
      downvotes
      tags
    }
    moderation_level
    number_of_users
  }
}
`;
export const onUpdateCommunity = `subscription OnUpdateCommunity {
  onUpdateCommunity {
    id
    url
    name
    description
    creator
    created_date
    rules {
      id
      community_id
      summary
      explanation
    }
    locations
    hidden
    hidden_date
    sitewide_reasons_for_being_hidden
    keywords
    tags
    flagged_comments {
      id
      content
      creator
      discussionId
      created_date
      hidden
      hidden_date
      sitewide_reasons_for_being_hidden
      community_reasons_for_being_hidden
      contributed_to_discussion
      did_not_contribute_to_discussion
      agree
      disagree
      funny
      date_last_modified
      parent_comment_id
    }
    flagged_discussions {
      id
      title
      creator
      communityUrl
      createdDate
      content
      locked
      hidden
      sitewide_reasons_for_being_hidden
      community_reasons_for_being_hidden
      hidden_date
      upvotes
      downvotes
      tags
    }
    moderation_level
    number_of_users
  }
}
`;
export const onDeleteCommunity = `subscription OnDeleteCommunity {
  onDeleteCommunity {
    id
    url
    name
    description
    creator
    created_date
    rules {
      id
      community_id
      summary
      explanation
    }
    locations
    hidden
    hidden_date
    sitewide_reasons_for_being_hidden
    keywords
    tags
    flagged_comments {
      id
      content
      creator
      discussionId
      created_date
      hidden
      hidden_date
      sitewide_reasons_for_being_hidden
      community_reasons_for_being_hidden
      contributed_to_discussion
      did_not_contribute_to_discussion
      agree
      disagree
      funny
      date_last_modified
      parent_comment_id
    }
    flagged_discussions {
      id
      title
      creator
      communityUrl
      createdDate
      content
      locked
      hidden
      sitewide_reasons_for_being_hidden
      community_reasons_for_being_hidden
      hidden_date
      upvotes
      downvotes
      tags
    }
    moderation_level
    number_of_users
  }
}
`;
export const onCreateRule = `subscription OnCreateRule {
  onCreateRule {
    id
    community_id
    summary
    explanation
  }
}
`;
export const onUpdateRule = `subscription OnUpdateRule {
  onUpdateRule {
    id
    community_id
    summary
    explanation
  }
}
`;
export const onDeleteRule = `subscription OnDeleteRule {
  onDeleteRule {
    id
    community_id
    summary
    explanation
  }
}
`;
export const onCreateBan = `subscription OnCreateBan {
  onCreateBan {
    id
    user {
      id
      email
      profiles {
        id
        username
        real_sounding_name
        bio
        pronouns
        location
        picture
        reputation
        account_created_date
      }
      default_profile {
        id
        username
        real_sounding_name
        bio
        pronouns
        location
        picture
        reputation
        account_created_date
      }
    }
    is_sitewide_ban
    community {
      id
      url
      name
      description
      creator
      created_date
      rules {
        id
        community_id
        summary
        explanation
      }
      locations
      hidden
      hidden_date
      sitewide_reasons_for_being_hidden
      keywords
      tags
      flagged_comments {
        id
        content
        creator
        discussionId
        created_date
        hidden
        hidden_date
        sitewide_reasons_for_being_hidden
        community_reasons_for_being_hidden
        contributed_to_discussion
        did_not_contribute_to_discussion
        agree
        disagree
        funny
        date_last_modified
        parent_comment_id
      }
      flagged_discussions {
        id
        title
        creator
        communityUrl
        createdDate
        content
        locked
        hidden
        sitewide_reasons_for_being_hidden
        community_reasons_for_being_hidden
        hidden_date
        upvotes
        downvotes
        tags
      }
      moderation_level
      number_of_users
    }
    createdDate
    expirationDate
  }
}
`;
export const onUpdateBan = `subscription OnUpdateBan {
  onUpdateBan {
    id
    user {
      id
      email
      profiles {
        id
        username
        real_sounding_name
        bio
        pronouns
        location
        picture
        reputation
        account_created_date
      }
      default_profile {
        id
        username
        real_sounding_name
        bio
        pronouns
        location
        picture
        reputation
        account_created_date
      }
    }
    is_sitewide_ban
    community {
      id
      url
      name
      description
      creator
      created_date
      rules {
        id
        community_id
        summary
        explanation
      }
      locations
      hidden
      hidden_date
      sitewide_reasons_for_being_hidden
      keywords
      tags
      flagged_comments {
        id
        content
        creator
        discussionId
        created_date
        hidden
        hidden_date
        sitewide_reasons_for_being_hidden
        community_reasons_for_being_hidden
        contributed_to_discussion
        did_not_contribute_to_discussion
        agree
        disagree
        funny
        date_last_modified
        parent_comment_id
      }
      flagged_discussions {
        id
        title
        creator
        communityUrl
        createdDate
        content
        locked
        hidden
        sitewide_reasons_for_being_hidden
        community_reasons_for_being_hidden
        hidden_date
        upvotes
        downvotes
        tags
      }
      moderation_level
      number_of_users
    }
    createdDate
    expirationDate
  }
}
`;
export const onDeleteBan = `subscription OnDeleteBan {
  onDeleteBan {
    id
    user {
      id
      email
      profiles {
        id
        username
        real_sounding_name
        bio
        pronouns
        location
        picture
        reputation
        account_created_date
      }
      default_profile {
        id
        username
        real_sounding_name
        bio
        pronouns
        location
        picture
        reputation
        account_created_date
      }
    }
    is_sitewide_ban
    community {
      id
      url
      name
      description
      creator
      created_date
      rules {
        id
        community_id
        summary
        explanation
      }
      locations
      hidden
      hidden_date
      sitewide_reasons_for_being_hidden
      keywords
      tags
      flagged_comments {
        id
        content
        creator
        discussionId
        created_date
        hidden
        hidden_date
        sitewide_reasons_for_being_hidden
        community_reasons_for_being_hidden
        contributed_to_discussion
        did_not_contribute_to_discussion
        agree
        disagree
        funny
        date_last_modified
        parent_comment_id
      }
      flagged_discussions {
        id
        title
        creator
        communityUrl
        createdDate
        content
        locked
        hidden
        sitewide_reasons_for_being_hidden
        community_reasons_for_being_hidden
        hidden_date
        upvotes
        downvotes
        tags
      }
      moderation_level
      number_of_users
    }
    createdDate
    expirationDate
  }
}
`;
export const onCreateComment = `subscription OnCreateComment {
  onCreateComment {
    id
    content
    creator
    discussionId
    created_date
    hidden
    hidden_date
    sitewide_reasons_for_being_hidden
    community_reasons_for_being_hidden
    contributed_to_discussion
    did_not_contribute_to_discussion
    agree
    disagree
    funny
    date_last_modified
    parent_comment_id
  }
}
`;
export const onUpdateComment = `subscription OnUpdateComment {
  onUpdateComment {
    id
    content
    creator
    discussionId
    created_date
    hidden
    hidden_date
    sitewide_reasons_for_being_hidden
    community_reasons_for_being_hidden
    contributed_to_discussion
    did_not_contribute_to_discussion
    agree
    disagree
    funny
    date_last_modified
    parent_comment_id
  }
}
`;
export const onDeleteComment = `subscription OnDeleteComment {
  onDeleteComment {
    id
    content
    creator
    discussionId
    created_date
    hidden
    hidden_date
    sitewide_reasons_for_being_hidden
    community_reasons_for_being_hidden
    contributed_to_discussion
    did_not_contribute_to_discussion
    agree
    disagree
    funny
    date_last_modified
    parent_comment_id
  }
}
`;
export const onCreateDiscussion = `subscription OnCreateDiscussion {
  onCreateDiscussion {
    id
    title
    creator
    communityUrl
    createdDate
    content
    locked
    hidden
    sitewide_reasons_for_being_hidden
    community_reasons_for_being_hidden
    hidden_date
    upvotes
    downvotes
    tags
  }
}
`;
export const onUpdateDiscussion = `subscription OnUpdateDiscussion {
  onUpdateDiscussion {
    id
    title
    creator
    communityUrl
    createdDate
    content
    locked
    hidden
    sitewide_reasons_for_being_hidden
    community_reasons_for_being_hidden
    hidden_date
    upvotes
    downvotes
    tags
  }
}
`;
export const onDeleteDiscussion = `subscription OnDeleteDiscussion {
  onDeleteDiscussion {
    id
    title
    creator
    communityUrl
    createdDate
    content
    locked
    hidden
    sitewide_reasons_for_being_hidden
    community_reasons_for_being_hidden
    hidden_date
    upvotes
    downvotes
    tags
  }
}
`;
export const onCreateEvent = `subscription OnCreateEvent {
  onCreateEvent {
    id
    title
    description
    picture
    start_time
    end_time
    place {
      id
      url
      name
      description
      creator
      created_date
      rules {
        id
        community_id
        summary
        explanation
      }
      locations
      hidden
      hidden_date
      sitewide_reasons_for_being_hidden
      keywords
      tags
      flagged_comments {
        id
        content
        creator
        discussionId
        created_date
        hidden
        hidden_date
        sitewide_reasons_for_being_hidden
        community_reasons_for_being_hidden
        contributed_to_discussion
        did_not_contribute_to_discussion
        agree
        disagree
        funny
        date_last_modified
        parent_comment_id
      }
      flagged_discussions {
        id
        title
        creator
        communityUrl
        createdDate
        content
        locked
        hidden
        sitewide_reasons_for_being_hidden
        community_reasons_for_being_hidden
        hidden_date
        upvotes
        downvotes
        tags
      }
      moderation_level
      number_of_users
    }
    organizer {
      id
      email
      profiles {
        id
        username
        real_sounding_name
        bio
        pronouns
        location
        picture
        reputation
        account_created_date
      }
      default_profile {
        id
        username
        real_sounding_name
        bio
        pronouns
        location
        picture
        reputation
        account_created_date
      }
    }
  }
}
`;
export const onUpdateEvent = `subscription OnUpdateEvent {
  onUpdateEvent {
    id
    title
    description
    picture
    start_time
    end_time
    place {
      id
      url
      name
      description
      creator
      created_date
      rules {
        id
        community_id
        summary
        explanation
      }
      locations
      hidden
      hidden_date
      sitewide_reasons_for_being_hidden
      keywords
      tags
      flagged_comments {
        id
        content
        creator
        discussionId
        created_date
        hidden
        hidden_date
        sitewide_reasons_for_being_hidden
        community_reasons_for_being_hidden
        contributed_to_discussion
        did_not_contribute_to_discussion
        agree
        disagree
        funny
        date_last_modified
        parent_comment_id
      }
      flagged_discussions {
        id
        title
        creator
        communityUrl
        createdDate
        content
        locked
        hidden
        sitewide_reasons_for_being_hidden
        community_reasons_for_being_hidden
        hidden_date
        upvotes
        downvotes
        tags
      }
      moderation_level
      number_of_users
    }
    organizer {
      id
      email
      profiles {
        id
        username
        real_sounding_name
        bio
        pronouns
        location
        picture
        reputation
        account_created_date
      }
      default_profile {
        id
        username
        real_sounding_name
        bio
        pronouns
        location
        picture
        reputation
        account_created_date
      }
    }
  }
}
`;
export const onDeleteEvent = `subscription OnDeleteEvent {
  onDeleteEvent {
    id
    title
    description
    picture
    start_time
    end_time
    place {
      id
      url
      name
      description
      creator
      created_date
      rules {
        id
        community_id
        summary
        explanation
      }
      locations
      hidden
      hidden_date
      sitewide_reasons_for_being_hidden
      keywords
      tags
      flagged_comments {
        id
        content
        creator
        discussionId
        created_date
        hidden
        hidden_date
        sitewide_reasons_for_being_hidden
        community_reasons_for_being_hidden
        contributed_to_discussion
        did_not_contribute_to_discussion
        agree
        disagree
        funny
        date_last_modified
        parent_comment_id
      }
      flagged_discussions {
        id
        title
        creator
        communityUrl
        createdDate
        content
        locked
        hidden
        sitewide_reasons_for_being_hidden
        community_reasons_for_being_hidden
        hidden_date
        upvotes
        downvotes
        tags
      }
      moderation_level
      number_of_users
    }
    organizer {
      id
      email
      profiles {
        id
        username
        real_sounding_name
        bio
        pronouns
        location
        picture
        reputation
        account_created_date
      }
      default_profile {
        id
        username
        real_sounding_name
        bio
        pronouns
        location
        picture
        reputation
        account_created_date
      }
    }
  }
}
`;
export const onCreatePrivateMessage = `subscription OnCreatePrivateMessage {
  onCreatePrivateMessage {
    id
    title
    content
    author {
      id
      email
      profiles {
        id
        username
        real_sounding_name
        bio
        pronouns
        location
        picture
        reputation
        account_created_date
      }
      default_profile {
        id
        username
        real_sounding_name
        bio
        pronouns
        location
        picture
        reputation
        account_created_date
      }
    }
    sentDate
  }
}
`;
export const onUpdatePrivateMessage = `subscription OnUpdatePrivateMessage {
  onUpdatePrivateMessage {
    id
    title
    content
    author {
      id
      email
      profiles {
        id
        username
        real_sounding_name
        bio
        pronouns
        location
        picture
        reputation
        account_created_date
      }
      default_profile {
        id
        username
        real_sounding_name
        bio
        pronouns
        location
        picture
        reputation
        account_created_date
      }
    }
    sentDate
  }
}
`;
export const onDeletePrivateMessage = `subscription OnDeletePrivateMessage {
  onDeletePrivateMessage {
    id
    title
    content
    author {
      id
      email
      profiles {
        id
        username
        real_sounding_name
        bio
        pronouns
        location
        picture
        reputation
        account_created_date
      }
      default_profile {
        id
        username
        real_sounding_name
        bio
        pronouns
        location
        picture
        reputation
        account_created_date
      }
    }
    sentDate
  }
}
`;
export const onCreateReport = `subscription OnCreateReport {
  onCreateReport {
    id
    creator
    comment {
      id
      content
      creator
      discussionId
      created_date
      hidden
      hidden_date
      sitewide_reasons_for_being_hidden
      community_reasons_for_being_hidden
      contributed_to_discussion
      did_not_contribute_to_discussion
      agree
      disagree
      funny
      date_last_modified
      parent_comment_id
    }
    discussion {
      id
      title
      creator
      communityUrl
      createdDate
      content
      locked
      hidden
      sitewide_reasons_for_being_hidden
      community_reasons_for_being_hidden
      hidden_date
      upvotes
      downvotes
      tags
    }
    message {
      id
      title
      content
      author {
        id
        email
      }
      sentDate
    }
    complaint
    community {
      id
      url
      name
      description
      creator
      created_date
      rules {
        id
        community_id
        summary
        explanation
      }
      locations
      hidden
      hidden_date
      sitewide_reasons_for_being_hidden
      keywords
      tags
      flagged_comments {
        id
        content
        creator
        discussionId
        created_date
        hidden
        hidden_date
        sitewide_reasons_for_being_hidden
        community_reasons_for_being_hidden
        contributed_to_discussion
        did_not_contribute_to_discussion
        agree
        disagree
        funny
        date_last_modified
        parent_comment_id
      }
      flagged_discussions {
        id
        title
        creator
        communityUrl
        createdDate
        content
        locked
        hidden
        sitewide_reasons_for_being_hidden
        community_reasons_for_being_hidden
        hidden_date
        upvotes
        downvotes
        tags
      }
      moderation_level
      number_of_users
    }
    broken_sitewide_rules
    broken_community_rules
    author {
      id
      email
      profiles {
        id
        username
        real_sounding_name
        bio
        pronouns
        location
        picture
        reputation
        account_created_date
      }
      default_profile {
        id
        username
        real_sounding_name
        bio
        pronouns
        location
        picture
        reputation
        account_created_date
      }
    }
    created_date
    resolved
  }
}
`;
export const onUpdateReport = `subscription OnUpdateReport {
  onUpdateReport {
    id
    creator
    comment {
      id
      content
      creator
      discussionId
      created_date
      hidden
      hidden_date
      sitewide_reasons_for_being_hidden
      community_reasons_for_being_hidden
      contributed_to_discussion
      did_not_contribute_to_discussion
      agree
      disagree
      funny
      date_last_modified
      parent_comment_id
    }
    discussion {
      id
      title
      creator
      communityUrl
      createdDate
      content
      locked
      hidden
      sitewide_reasons_for_being_hidden
      community_reasons_for_being_hidden
      hidden_date
      upvotes
      downvotes
      tags
    }
    message {
      id
      title
      content
      author {
        id
        email
      }
      sentDate
    }
    complaint
    community {
      id
      url
      name
      description
      creator
      created_date
      rules {
        id
        community_id
        summary
        explanation
      }
      locations
      hidden
      hidden_date
      sitewide_reasons_for_being_hidden
      keywords
      tags
      flagged_comments {
        id
        content
        creator
        discussionId
        created_date
        hidden
        hidden_date
        sitewide_reasons_for_being_hidden
        community_reasons_for_being_hidden
        contributed_to_discussion
        did_not_contribute_to_discussion
        agree
        disagree
        funny
        date_last_modified
        parent_comment_id
      }
      flagged_discussions {
        id
        title
        creator
        communityUrl
        createdDate
        content
        locked
        hidden
        sitewide_reasons_for_being_hidden
        community_reasons_for_being_hidden
        hidden_date
        upvotes
        downvotes
        tags
      }
      moderation_level
      number_of_users
    }
    broken_sitewide_rules
    broken_community_rules
    author {
      id
      email
      profiles {
        id
        username
        real_sounding_name
        bio
        pronouns
        location
        picture
        reputation
        account_created_date
      }
      default_profile {
        id
        username
        real_sounding_name
        bio
        pronouns
        location
        picture
        reputation
        account_created_date
      }
    }
    created_date
    resolved
  }
}
`;
export const onDeleteReport = `subscription OnDeleteReport {
  onDeleteReport {
    id
    creator
    comment {
      id
      content
      creator
      discussionId
      created_date
      hidden
      hidden_date
      sitewide_reasons_for_being_hidden
      community_reasons_for_being_hidden
      contributed_to_discussion
      did_not_contribute_to_discussion
      agree
      disagree
      funny
      date_last_modified
      parent_comment_id
    }
    discussion {
      id
      title
      creator
      communityUrl
      createdDate
      content
      locked
      hidden
      sitewide_reasons_for_being_hidden
      community_reasons_for_being_hidden
      hidden_date
      upvotes
      downvotes
      tags
    }
    message {
      id
      title
      content
      author {
        id
        email
      }
      sentDate
    }
    complaint
    community {
      id
      url
      name
      description
      creator
      created_date
      rules {
        id
        community_id
        summary
        explanation
      }
      locations
      hidden
      hidden_date
      sitewide_reasons_for_being_hidden
      keywords
      tags
      flagged_comments {
        id
        content
        creator
        discussionId
        created_date
        hidden
        hidden_date
        sitewide_reasons_for_being_hidden
        community_reasons_for_being_hidden
        contributed_to_discussion
        did_not_contribute_to_discussion
        agree
        disagree
        funny
        date_last_modified
        parent_comment_id
      }
      flagged_discussions {
        id
        title
        creator
        communityUrl
        createdDate
        content
        locked
        hidden
        sitewide_reasons_for_being_hidden
        community_reasons_for_being_hidden
        hidden_date
        upvotes
        downvotes
        tags
      }
      moderation_level
      number_of_users
    }
    broken_sitewide_rules
    broken_community_rules
    author {
      id
      email
      profiles {
        id
        username
        real_sounding_name
        bio
        pronouns
        location
        picture
        reputation
        account_created_date
      }
      default_profile {
        id
        username
        real_sounding_name
        bio
        pronouns
        location
        picture
        reputation
        account_created_date
      }
    }
    created_date
    resolved
  }
}
`;
export const onCreateUser = `subscription OnCreateUser {
  onCreateUser {
    id
    email
    profiles {
      id
      username
      real_sounding_name
      bio
      pronouns
      location
      picture
      reputation
      account_created_date
      bans {
        id
        is_sitewide_ban
        createdDate
        expirationDate
      }
      member_of {
        id
        url
        name
        description
        creator
        created_date
        locations
        hidden
        hidden_date
        sitewide_reasons_for_being_hidden
        keywords
        tags
        moderation_level
        number_of_users
      }
      moderator_of {
        id
        url
        name
        description
        creator
        created_date
        locations
        hidden
        hidden_date
        sitewide_reasons_for_being_hidden
        keywords
        tags
        moderation_level
        number_of_users
      }
      creator_of {
        id
        url
        name
        description
        creator
        created_date
        locations
        hidden
        hidden_date
        sitewide_reasons_for_being_hidden
        keywords
        tags
        moderation_level
        number_of_users
      }
    }
    default_profile {
      id
      username
      real_sounding_name
      bio
      pronouns
      location
      picture
      reputation
      account_created_date
      bans {
        id
        is_sitewide_ban
        createdDate
        expirationDate
      }
      member_of {
        id
        url
        name
        description
        creator
        created_date
        locations
        hidden
        hidden_date
        sitewide_reasons_for_being_hidden
        keywords
        tags
        moderation_level
        number_of_users
      }
      moderator_of {
        id
        url
        name
        description
        creator
        created_date
        locations
        hidden
        hidden_date
        sitewide_reasons_for_being_hidden
        keywords
        tags
        moderation_level
        number_of_users
      }
      creator_of {
        id
        url
        name
        description
        creator
        created_date
        locations
        hidden
        hidden_date
        sitewide_reasons_for_being_hidden
        keywords
        tags
        moderation_level
        number_of_users
      }
    }
  }
}
`;
export const onUpdateUser = `subscription OnUpdateUser {
  onUpdateUser {
    id
    email
    profiles {
      id
      username
      real_sounding_name
      bio
      pronouns
      location
      picture
      reputation
      account_created_date
      bans {
        id
        is_sitewide_ban
        createdDate
        expirationDate
      }
      member_of {
        id
        url
        name
        description
        creator
        created_date
        locations
        hidden
        hidden_date
        sitewide_reasons_for_being_hidden
        keywords
        tags
        moderation_level
        number_of_users
      }
      moderator_of {
        id
        url
        name
        description
        creator
        created_date
        locations
        hidden
        hidden_date
        sitewide_reasons_for_being_hidden
        keywords
        tags
        moderation_level
        number_of_users
      }
      creator_of {
        id
        url
        name
        description
        creator
        created_date
        locations
        hidden
        hidden_date
        sitewide_reasons_for_being_hidden
        keywords
        tags
        moderation_level
        number_of_users
      }
    }
    default_profile {
      id
      username
      real_sounding_name
      bio
      pronouns
      location
      picture
      reputation
      account_created_date
      bans {
        id
        is_sitewide_ban
        createdDate
        expirationDate
      }
      member_of {
        id
        url
        name
        description
        creator
        created_date
        locations
        hidden
        hidden_date
        sitewide_reasons_for_being_hidden
        keywords
        tags
        moderation_level
        number_of_users
      }
      moderator_of {
        id
        url
        name
        description
        creator
        created_date
        locations
        hidden
        hidden_date
        sitewide_reasons_for_being_hidden
        keywords
        tags
        moderation_level
        number_of_users
      }
      creator_of {
        id
        url
        name
        description
        creator
        created_date
        locations
        hidden
        hidden_date
        sitewide_reasons_for_being_hidden
        keywords
        tags
        moderation_level
        number_of_users
      }
    }
  }
}
`;
export const onDeleteUser = `subscription OnDeleteUser {
  onDeleteUser {
    id
    email
    profiles {
      id
      username
      real_sounding_name
      bio
      pronouns
      location
      picture
      reputation
      account_created_date
      bans {
        id
        is_sitewide_ban
        createdDate
        expirationDate
      }
      member_of {
        id
        url
        name
        description
        creator
        created_date
        locations
        hidden
        hidden_date
        sitewide_reasons_for_being_hidden
        keywords
        tags
        moderation_level
        number_of_users
      }
      moderator_of {
        id
        url
        name
        description
        creator
        created_date
        locations
        hidden
        hidden_date
        sitewide_reasons_for_being_hidden
        keywords
        tags
        moderation_level
        number_of_users
      }
      creator_of {
        id
        url
        name
        description
        creator
        created_date
        locations
        hidden
        hidden_date
        sitewide_reasons_for_being_hidden
        keywords
        tags
        moderation_level
        number_of_users
      }
    }
    default_profile {
      id
      username
      real_sounding_name
      bio
      pronouns
      location
      picture
      reputation
      account_created_date
      bans {
        id
        is_sitewide_ban
        createdDate
        expirationDate
      }
      member_of {
        id
        url
        name
        description
        creator
        created_date
        locations
        hidden
        hidden_date
        sitewide_reasons_for_being_hidden
        keywords
        tags
        moderation_level
        number_of_users
      }
      moderator_of {
        id
        url
        name
        description
        creator
        created_date
        locations
        hidden
        hidden_date
        sitewide_reasons_for_being_hidden
        keywords
        tags
        moderation_level
        number_of_users
      }
      creator_of {
        id
        url
        name
        description
        creator
        created_date
        locations
        hidden
        hidden_date
        sitewide_reasons_for_being_hidden
        keywords
        tags
        moderation_level
        number_of_users
      }
    }
  }
}
`;
export const onCreateProfile = `subscription OnCreateProfile {
  onCreateProfile {
    id
    username
    real_sounding_name
    bio
    pronouns
    location
    picture
    reputation
    account_created_date
    bans {
      id
      user {
        id
        email
      }
      is_sitewide_ban
      community {
        id
        url
        name
        description
        creator
        created_date
        locations
        hidden
        hidden_date
        sitewide_reasons_for_being_hidden
        keywords
        tags
        moderation_level
        number_of_users
      }
      createdDate
      expirationDate
    }
    member_of {
      id
      url
      name
      description
      creator
      created_date
      rules {
        id
        community_id
        summary
        explanation
      }
      locations
      hidden
      hidden_date
      sitewide_reasons_for_being_hidden
      keywords
      tags
      flagged_comments {
        id
        content
        creator
        discussionId
        created_date
        hidden
        hidden_date
        sitewide_reasons_for_being_hidden
        community_reasons_for_being_hidden
        contributed_to_discussion
        did_not_contribute_to_discussion
        agree
        disagree
        funny
        date_last_modified
        parent_comment_id
      }
      flagged_discussions {
        id
        title
        creator
        communityUrl
        createdDate
        content
        locked
        hidden
        sitewide_reasons_for_being_hidden
        community_reasons_for_being_hidden
        hidden_date
        upvotes
        downvotes
        tags
      }
      moderation_level
      number_of_users
    }
    moderator_of {
      id
      url
      name
      description
      creator
      created_date
      rules {
        id
        community_id
        summary
        explanation
      }
      locations
      hidden
      hidden_date
      sitewide_reasons_for_being_hidden
      keywords
      tags
      flagged_comments {
        id
        content
        creator
        discussionId
        created_date
        hidden
        hidden_date
        sitewide_reasons_for_being_hidden
        community_reasons_for_being_hidden
        contributed_to_discussion
        did_not_contribute_to_discussion
        agree
        disagree
        funny
        date_last_modified
        parent_comment_id
      }
      flagged_discussions {
        id
        title
        creator
        communityUrl
        createdDate
        content
        locked
        hidden
        sitewide_reasons_for_being_hidden
        community_reasons_for_being_hidden
        hidden_date
        upvotes
        downvotes
        tags
      }
      moderation_level
      number_of_users
    }
    creator_of {
      id
      url
      name
      description
      creator
      created_date
      rules {
        id
        community_id
        summary
        explanation
      }
      locations
      hidden
      hidden_date
      sitewide_reasons_for_being_hidden
      keywords
      tags
      flagged_comments {
        id
        content
        creator
        discussionId
        created_date
        hidden
        hidden_date
        sitewide_reasons_for_being_hidden
        community_reasons_for_being_hidden
        contributed_to_discussion
        did_not_contribute_to_discussion
        agree
        disagree
        funny
        date_last_modified
        parent_comment_id
      }
      flagged_discussions {
        id
        title
        creator
        communityUrl
        createdDate
        content
        locked
        hidden
        sitewide_reasons_for_being_hidden
        community_reasons_for_being_hidden
        hidden_date
        upvotes
        downvotes
        tags
      }
      moderation_level
      number_of_users
    }
  }
}
`;
export const onUpdateProfile = `subscription OnUpdateProfile {
  onUpdateProfile {
    id
    username
    real_sounding_name
    bio
    pronouns
    location
    picture
    reputation
    account_created_date
    bans {
      id
      user {
        id
        email
      }
      is_sitewide_ban
      community {
        id
        url
        name
        description
        creator
        created_date
        locations
        hidden
        hidden_date
        sitewide_reasons_for_being_hidden
        keywords
        tags
        moderation_level
        number_of_users
      }
      createdDate
      expirationDate
    }
    member_of {
      id
      url
      name
      description
      creator
      created_date
      rules {
        id
        community_id
        summary
        explanation
      }
      locations
      hidden
      hidden_date
      sitewide_reasons_for_being_hidden
      keywords
      tags
      flagged_comments {
        id
        content
        creator
        discussionId
        created_date
        hidden
        hidden_date
        sitewide_reasons_for_being_hidden
        community_reasons_for_being_hidden
        contributed_to_discussion
        did_not_contribute_to_discussion
        agree
        disagree
        funny
        date_last_modified
        parent_comment_id
      }
      flagged_discussions {
        id
        title
        creator
        communityUrl
        createdDate
        content
        locked
        hidden
        sitewide_reasons_for_being_hidden
        community_reasons_for_being_hidden
        hidden_date
        upvotes
        downvotes
        tags
      }
      moderation_level
      number_of_users
    }
    moderator_of {
      id
      url
      name
      description
      creator
      created_date
      rules {
        id
        community_id
        summary
        explanation
      }
      locations
      hidden
      hidden_date
      sitewide_reasons_for_being_hidden
      keywords
      tags
      flagged_comments {
        id
        content
        creator
        discussionId
        created_date
        hidden
        hidden_date
        sitewide_reasons_for_being_hidden
        community_reasons_for_being_hidden
        contributed_to_discussion
        did_not_contribute_to_discussion
        agree
        disagree
        funny
        date_last_modified
        parent_comment_id
      }
      flagged_discussions {
        id
        title
        creator
        communityUrl
        createdDate
        content
        locked
        hidden
        sitewide_reasons_for_being_hidden
        community_reasons_for_being_hidden
        hidden_date
        upvotes
        downvotes
        tags
      }
      moderation_level
      number_of_users
    }
    creator_of {
      id
      url
      name
      description
      creator
      created_date
      rules {
        id
        community_id
        summary
        explanation
      }
      locations
      hidden
      hidden_date
      sitewide_reasons_for_being_hidden
      keywords
      tags
      flagged_comments {
        id
        content
        creator
        discussionId
        created_date
        hidden
        hidden_date
        sitewide_reasons_for_being_hidden
        community_reasons_for_being_hidden
        contributed_to_discussion
        did_not_contribute_to_discussion
        agree
        disagree
        funny
        date_last_modified
        parent_comment_id
      }
      flagged_discussions {
        id
        title
        creator
        communityUrl
        createdDate
        content
        locked
        hidden
        sitewide_reasons_for_being_hidden
        community_reasons_for_being_hidden
        hidden_date
        upvotes
        downvotes
        tags
      }
      moderation_level
      number_of_users
    }
  }
}
`;
export const onDeleteProfile = `subscription OnDeleteProfile {
  onDeleteProfile {
    id
    username
    real_sounding_name
    bio
    pronouns
    location
    picture
    reputation
    account_created_date
    bans {
      id
      user {
        id
        email
      }
      is_sitewide_ban
      community {
        id
        url
        name
        description
        creator
        created_date
        locations
        hidden
        hidden_date
        sitewide_reasons_for_being_hidden
        keywords
        tags
        moderation_level
        number_of_users
      }
      createdDate
      expirationDate
    }
    member_of {
      id
      url
      name
      description
      creator
      created_date
      rules {
        id
        community_id
        summary
        explanation
      }
      locations
      hidden
      hidden_date
      sitewide_reasons_for_being_hidden
      keywords
      tags
      flagged_comments {
        id
        content
        creator
        discussionId
        created_date
        hidden
        hidden_date
        sitewide_reasons_for_being_hidden
        community_reasons_for_being_hidden
        contributed_to_discussion
        did_not_contribute_to_discussion
        agree
        disagree
        funny
        date_last_modified
        parent_comment_id
      }
      flagged_discussions {
        id
        title
        creator
        communityUrl
        createdDate
        content
        locked
        hidden
        sitewide_reasons_for_being_hidden
        community_reasons_for_being_hidden
        hidden_date
        upvotes
        downvotes
        tags
      }
      moderation_level
      number_of_users
    }
    moderator_of {
      id
      url
      name
      description
      creator
      created_date
      rules {
        id
        community_id
        summary
        explanation
      }
      locations
      hidden
      hidden_date
      sitewide_reasons_for_being_hidden
      keywords
      tags
      flagged_comments {
        id
        content
        creator
        discussionId
        created_date
        hidden
        hidden_date
        sitewide_reasons_for_being_hidden
        community_reasons_for_being_hidden
        contributed_to_discussion
        did_not_contribute_to_discussion
        agree
        disagree
        funny
        date_last_modified
        parent_comment_id
      }
      flagged_discussions {
        id
        title
        creator
        communityUrl
        createdDate
        content
        locked
        hidden
        sitewide_reasons_for_being_hidden
        community_reasons_for_being_hidden
        hidden_date
        upvotes
        downvotes
        tags
      }
      moderation_level
      number_of_users
    }
    creator_of {
      id
      url
      name
      description
      creator
      created_date
      rules {
        id
        community_id
        summary
        explanation
      }
      locations
      hidden
      hidden_date
      sitewide_reasons_for_being_hidden
      keywords
      tags
      flagged_comments {
        id
        content
        creator
        discussionId
        created_date
        hidden
        hidden_date
        sitewide_reasons_for_being_hidden
        community_reasons_for_being_hidden
        contributed_to_discussion
        did_not_contribute_to_discussion
        agree
        disagree
        funny
        date_last_modified
        parent_comment_id
      }
      flagged_discussions {
        id
        title
        creator
        communityUrl
        createdDate
        content
        locked
        hidden
        sitewide_reasons_for_being_hidden
        community_reasons_for_being_hidden
        hidden_date
        upvotes
        downvotes
        tags
      }
      moderation_level
      number_of_users
    }
  }
}
`;
